services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    env_file: ./app_bot/.env
    working_dir: /app/app_bot
    networks:
      - app-network
    depends_on:
      - api
    restart: on-failure:5

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file: ./app_fastapi/.env
    working_dir: /app
    volumes:
      - innoscream-data:/app/db
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  innoscream-data:
  
networks:
  app-network:
    driver: bridge
