services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    env_file: ./app_bot/.env
    working_dir: /app/app_bot
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file: ./app_fastapi/.env
    working_dir: /app
    volumes:
      - ./db:/app/app_fastapi/db
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
