FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

WORKDIR /app
COPY pyproject.toml poetry.lock ./
COPY app_bot ./app_bot

RUN poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi

ENV PYTHONPATH=/app

CMD ["python", "main.py"]
