name: Bot-CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'app_bot/**'

jobs:
  app_bot_ci:
    name: Test & Lint app_bot
    runs-on: ubuntu-latest
    environment: app_api_env

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install project & dev-deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create true
          poetry install --no-interaction --no-ansi

      - name: Generate .env for app_bot
        run: |
          cat <<EOF > app_bot/.env
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          API_URL=${{ secrets.API_URL }}
          EOF

      - name: Run pytest with coverage
        working-directory: app_bot
        run: |
          poetry run pytest \
            --cov=. \
            --cov-report=term-missing \
            --cov-fail-under=60 \
            .

      - name: Check code complexity (radon)
        working-directory: app_bot
        run: |
          echo "Checking cyclomatic complexity ≤ 10 for all code blocks…"
          failures=$(
            poetry run radon cc . -s | \
            awk '/\([0-9]+\)$/{ gsub(/[()]/,"",$NF); if ($NF > 10) print }'
          )
          if [ -n "$failures" ]; then
            echo "Cyclomatic complexity threshold exceeded in:" >&2
            echo "$failures" >&2
            exit 1
          fi
          echo "All code blocks have complexity ≤ 10"

      - name: Lint with flake8
        run: flake8 app_bot/

      - name: Security scan with Bandit
        run: bandit -r app_bot/ -s B101,B311

      - name: Check docstrings (pydocstyle)
        working-directory: app_bot
        run: poetry run pydocstyle --select=D102,D103 .